# Generated by Django 5.0.2 on 2024-02-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sample_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='price',
            new_name='Agirlik',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='title1',
            new_name='Kategori',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='title2',
            new_name='Marka',
        ),
        migrations.AddField(
            model_name='sample',
            name='Model',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
